version: '3.8'

services:
  opensearch:
    image: opensearchproject/opensearch:2.19.1
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - "DISABLE_INSTALL_DEMO_CONFIG=false"
      - "DISABLE_SECURITY_PLUGIN=false"
      - "OPENSEARCH_SECURITY_SSL_ONLY=true"
      - "OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCH_PASS}"
      - "plugins.security.ssl.transport.pemcert_filepath=/usr/share/opensearch/config/certs/opensearch.crt"
      - "plugins.security.ssl.transport.pemtrustedcas_filepath=/usr/share/opensearch/config/certs/opensearch.crt"
      - "plugins.security.ssl.transport.pemkey_filepath=/usr/share/opensearch/config/certs/opensearch.key"
      - "plugins.security.ssl.http.enabled=true"
      - "plugins.security.ssl.http.pemcert_filepath=/usr/share/opensearch/config/certs/opensearch.crt"
      - "plugins.security.ssl.http.pemkey_filepath=/usr/share/opensearch/config/certs/opensearch.key"
      - "plugins.security.ssl.http.pemtrustedcas_filepath=/usr/share/opensearch/config/certs/opensearch.crt"
    volumes:
      - ./certs:/usr/share/opensearch/config/certs
      - /inoichi/opensearch-data:/usr/share/opensearch/data
    ports:
      - "9200:9200"
      - "9600:9600"
    networks:
      - opensearch-net

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.19.1
    ports:
      - "5601:5601"
    environment:
      - 'OPENSEARCH_HOSTS=["https://opensearch:9200"]'
      - 'SERVER_SSL_ENABLED=true'
      - 'SERVER_SSL_CERTIFICATE=/usr/share/opensearch-dashboards/config/certs/opensearch.crt'
      - 'SERVER_SSL_KEY=/usr/share/opensearch-dashboards/config/certs/opensearch.key'
      - "DISABLE_SECURITY_DASHBOARDS_PLUGIN=false"
      - "OPENSEARCH_SSL_VERIFICATIONMODE=none"
    volumes:
      - ./certs:/usr/share/opensearch-dashboards/config/certs
    networks:
      - opensearch-net
    depends_on:
      - opensearch

networks:
  opensearch-net:    # Change this to external

volumes:
  opensearch_data:
